spring:
  application:
    name: agent-server

server:
  port: 8001

agent:
  base:
    path: /opt/web/agent
  llm:
    file: llm_conf.json
  session:
    file: session.json
  memory:
    file: memory.json
  rag:
    file: rag

