spring:
  application:
    name: agent-server
  main:
    allow-circular-references: true

server:
  port: 8001

agent:
  base:
    path: /opt/web/agent
  llm:
    folder: llm
    file: llm_conf.json
  session:
    folder: session
    file: session.json
  memory:
    folder: memory
    file: memory.json
  rag:
    folder: rag
  embedding:
    folder: embed
    file: embed.json


