spring:
  application:
    name: agent-server
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8070

agent:
  base:
    path: /opt/web/agent
  llm:
    folder: llm
    file: llm_conf.json
  session:
    folder: session
    file: session.json
  memory:
    folder: memory
    file: memory.json
  rag:
    folder: rag
  mcp:
    folder: mcp
    file: mcp_conf.json
  prompt:
    folder: prompt
    file: system_prompt.json
